# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # release:
  #   types: [created,published]
  push:
    branches: [ master ]
    paths:
      - '**.psd1'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publishmodule:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            main:
              - 'code365scripts/*.psd1'
            core:
              - 'code365scripts.core/*.psd1'
            teams:
              - 'code365scripts.teams/*.psd1'
            weixin:
              - 'code365scripts.weixin/*.psd1'
            sandbox:
              - 'code365scripts.sandbox/*.psd1'

      - if: steps.changes.outputs.main == 'true'
        name: Code signing (main)
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'code365scripts'
          recursive: true
          files: |
            *.ps1
        # run only if some file in 'src' folder was changed
      - name: Publish Module to PowerShell Gallery (main)
        if: steps.changes.outputs.main == 'true'
        uses: chenxizhang/publish-powershell-module-action@v35
        id: publish-main
        with:
          modulePath: code365scripts
          NuGetApiKey: ${{ secrets.NUGETKEY }}
          dependencies: code365scripts.core,code365scripts.teams,code365scripts.weixin

      - if: steps.changes.outputs.core == 'true'
        name: Code signing (core)
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'code365scripts.core'
          recursive: true
          files: |
            *.ps1
      - name: Publish Module to PowerShell Gallery (core)
        if: steps.changes.outputs.core == 'true'
        uses: chenxizhang/publish-powershell-module-action@v35
        id: publish-core
        with:
          modulePath: code365scripts.core
          NuGetApiKey: ${{ secrets.NUGETKEY }}

      - if: steps.changes.outputs.teams == 'true'
        name: Code signing (teams)
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'code365scripts.teams'
          recursive: true
          files: |
            *.ps1
          
      - name: Publish Module to PowerShell Gallery (teams)
        if: steps.changes.outputs.teams == 'true'
        uses: chenxizhang/publish-powershell-module-action@v35
        id: publish-teams
        with:
          modulePath: code365scripts.teams
          NuGetApiKey: ${{ secrets.NUGETKEY }}

      - if: steps.changes.outputs.weixin == 'true'
        name: Code signing (weixin)
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'code365scripts.weixin'
          recursive: true
          files: |
            *.ps1

      - name: Publish Module to PowerShell Gallery (weixin)
        if: steps.changes.outputs.weixin == 'true'
        uses: chenxizhang/publish-powershell-module-action@v35
        id: publish-weixin
        with:
          modulePath: code365scripts.weixin
          NuGetApiKey: ${{ secrets.NUGETKEY }}

      - if: steps.changes.outputs.sandbox == 'true'
        name: Code signing (sandbox)
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'code365scripts.sandbox'
          recursive: true
          files: |
            *.ps1

      - name: Publish Module to PowerShell Gallery (weixin)
        if: steps.changes.outputs.sandbox == 'true'
        uses: chenxizhang/publish-powershell-module-action@v35
        id: publish-sandbox
        with:
          modulePath: code365scripts.sandbox
          NuGetApiKey: ${{ secrets.NUGETKEY }}